### Portfolio and Risk

* Pandas Datareader
* Pandas
* Numpy(focus in this course)
* Portfolio and return

##### Pandas Datareader & Pandas DataFrame

In [2]:
import numpy as np
import pandas_datareader as pdr
import datetime as dt
import pandas as pd

In [3]:
start = dt.datetime(2020,1,1)
ticker = "AAPL"
data = pdr.get_data_stooq(ticker,start,end)

In [21]:
data = data[::-1]

In [17]:
data.dtypes

Open      float64
High      float64
Low       float64
Close     float64
Volume    float64
dtype: object

In [22]:
data.head()

Open     High      Low    Close        Volume
Date                                                        
2020-01-02  72.5537  73.6225  72.2955  73.5616  1.384613e+08
2020-01-03  72.7790  73.6185  72.6185  72.8488  1.495753e+08
2020-01-06  71.9515  73.4649  71.7023  73.4250  1.210384e+08
2020-01-07  73.4350  73.6972  72.8607  73.0831  1.138238e+08
2020-01-08  72.7810  74.5626  72.7790  74.2575  1.351095e+08

In [19]:
data.tail()

Open     High       Low   Close      Volume
Date                                                      
2023-03-08  152.810  153.470  151.8300  152.87  47204791.0
2023-03-09  153.559  154.535  150.2250  150.59  53833582.0
2023-03-10  150.210  150.940  147.6096  148.50  68572400.0
2023-03-13  147.805  153.140  147.7000  150.47  84457122.0
2023-03-14  151.280  153.400  150.1000  152.59  73695893.0

In [23]:
type(data)

pandas.core.frame.DataFrame

##### NumPy

In [24]:
data.to_numpy()

array([[7.25537000e+01, 7.36225000e+01, 7.22955000e+01, 7.35616000e+01,
        1.38461336e+08],
       [7.27790000e+01, 7.36185000e+01, 7.26185000e+01, 7.28488000e+01,
        1.49575255e+08],
       [7.19515000e+01, 7.34649000e+01, 7.17023000e+01, 7.34250000e+01,
        1.21038376e+08],
       ...,
       [1.50210000e+02, 1.50940000e+02, 1.47609600e+02, 1.48500000e+02,
        6.85724000e+07],
       [1.47805000e+02, 1.53140000e+02, 1.47700000e+02, 1.50470000e+02,
        8.44571220e+07],
       [1.51280000e+02, 1.53400000e+02, 1.50100000e+02, 1.52590000e+02,
        7.36958930e+07]])

In [25]:
arr = data.to_numpy()

In [26]:
arr.shape

(805, 5)

In [27]:
len(data)

805

In [28]:
arr[0]

array([7.25537000e+01, 7.36225000e+01, 7.22955000e+01, 7.35616000e+01,
       1.38461336e+08])

In [29]:
data.head(1)

Open     High      Low    Close        Volume
Date                                                        
2020-01-02  72.5537  73.6225  72.2955  73.5616  1.384613e+08

In [30]:
arr.dtype

dtype('float64')

In [31]:
small = arr[:10,1].copy()

In [32]:
small

array([73.6225, 73.6185, 73.4649, 73.6972, 74.5626, 76.0261, 76.5785,
       77.6581, 77.7788, 77.2723])

In [33]:
data.head()

Open     High      Low    Close        Volume
Date                                                        
2020-01-02  72.5537  73.6225  72.2955  73.5616  1.384613e+08
2020-01-03  72.7790  73.6185  72.6185  72.8488  1.495753e+08
2020-01-06  71.9515  73.4649  71.7023  73.4250  1.210384e+08
2020-01-07  73.4350  73.6972  72.8607  73.0831  1.138238e+08
2020-01-08  72.7810  74.5626  72.7790  74.2575  1.351095e+08

In [34]:
np.max(small)

77.7788

In [35]:
small.max()

77.7788

In [36]:
small.argmax()

8

In [37]:
small[small.argmax()]

77.7788

In [38]:
np.log(small)

array([4.29895069, 4.29889635, 4.29680774, 4.29996481, 4.31163904,
       4.3310767 , 4.33831636, 4.35231586, 4.3538689 , 4.34733555])

In [39]:
np.log(data)

Open      High       Low     Close     Volume
Date                                                         
2020-01-02  4.284327  4.298951  4.280762  4.298123  18.746102
2020-01-03  4.287427  4.298896  4.285220  4.288386  18.823310
2020-01-06  4.275992  4.296808  4.272523  4.296264  18.611618
2020-01-07  4.296401  4.299965  4.288549  4.291597  18.550162
2020-01-08  4.287455  4.311639  4.287427  4.307539  18.721596
...              ...       ...       ...       ...        ...
2023-03-08  5.029195  5.033505  5.022761  5.029588  17.670006
2023-03-09  5.034085  5.040421  5.012134  5.014561  17.801408
2023-03-10  5.012034  5.016882  4.994571  5.000585  18.043401
2023-03-13  4.995894  5.031353  4.995183  5.013764  18.251755
2023-03-14  5.019132  5.033049  5.011302  5.027755  18.115458

[805 rows x 5 columns]

In [40]:
data/data.shift()

Open      High       Low     Close    Volume
Date                                                        
2020-01-02       NaN       NaN       NaN       NaN       NaN
2020-01-03  1.003105  0.999946  1.004468  0.990310  1.080267
2020-01-06  0.988630  0.997914  0.987383  1.007910  0.809214
2020-01-07  1.020618  1.003162  1.016156  0.995344  0.940394
2020-01-08  0.991094  1.011743  0.998879  1.016069  1.187006
...              ...       ...       ...       ...       ...
2023-03-08  0.994209  0.996365  1.004632  1.008377  0.840212
2023-03-09  1.004902  1.006939  0.989429  0.985085  1.140426
2023-03-10  0.978191  0.976737  0.982590  0.986121  1.273785
2023-03-13  0.983989  1.014575  1.000612  1.013266  1.231649
2023-03-14  1.023511  1.001698  1.016249  1.014089  0.872584

[805 rows x 5 columns]

In [42]:
np.sum(np.log(data/data.shift()))

Open      0.734805
High      0.734098
Low       0.730540
Close     0.729631
Volume   -0.630644
dtype: float64

In [43]:
np.log(data/data.iloc[0]).tail(1)

Open      High      Low     Close    Volume
Date                                                       
2023-03-14  0.734805  0.734098  0.73054  0.729631 -0.630644

In [45]:
small.shape

(10,)

In [46]:
small.reshape(2,5)

array([[73.6225, 73.6185, 73.4649, 73.6972, 74.5626],
       [76.0261, 76.5785, 77.6581, 77.7788, 77.2723]])

In [47]:
small.reshape(10,1)

array([[73.6225],
       [73.6185],
       [73.4649],
       [73.6972],
       [74.5626],
       [76.0261],
       [76.5785],
       [77.6581],
       [77.7788],
       [77.2723]])

In [48]:
small.reshape(-1,1)

array([[73.6225],
       [73.6185],
       [73.4649],
       [73.6972],
       [74.5626],
       [76.0261],
       [76.5785],
       [77.6581],
       [77.7788],
       [77.2723]])

##### Portfolios

In [49]:
tickers = ["AAPL","MSFT","TWTR","IBM"]
start = dt.datetime(2020,1,1)
data = pdr.get_data_stooq(tickers,start)

In [52]:
data = data[::-1]

In [53]:
data.head()

Attributes    Close                       High                        Low  \
Symbols        AAPL     MSFT      IBM     AAPL     MSFT      IBM     AAPL   
2020-01-02  73.5616  156.133  116.720  73.6225  156.231  117.159  72.2955   
2020-01-03  72.8488  154.216  115.784  73.6185  155.517  116.242  72.6185   
2020-01-06  73.4250  154.613  115.569  73.4649  154.683  115.696  71.7023   
2020-01-07  73.0831  153.183  115.656  73.6972  155.249  116.330  72.8607   
2020-01-08  74.2575  155.656  116.623  74.5626  156.301  117.111  72.7790   

Attributes                       Open                          Volume  \
Symbols        MSFT      IBM     AAPL     MSFT      IBM          AAPL   
2020-01-02  153.928  116.154  72.5537  154.365  116.359  1.384613e+08   
2020-01-03  153.660  115.119  72.7790  153.918  115.129  1.495753e+08   
2020-01-06  152.141  114.797  71.9515  152.688  114.993  1.210384e+08   
2020-01-07  152.925  114.973  73.4350  154.900  115.227  1.138238e+08   
2020-01-08  153.551  115.432  72.7810  154.514  115.940  1.351095e+08   

Attributes                              
Symbols             MSFT           IBM  
2020-01-02  2.328220e+07  3.653332e+06  
2020-01-03  2.172604e+07  2.753980e+06  
2020-01-06  2.142262e+07  2.815041e+06  
2020-01-07  2.250785e+07  3.800835e+06  
2020-01-08  2.855639e+07  5.042468e+06

In [54]:
data = data['Close']

In [55]:
data

Symbols         AAPL     MSFT      IBM
2020-01-02   73.5616  156.133  116.720
2020-01-03   72.8488  154.216  115.784
2020-01-06   73.4250  154.613  115.569
2020-01-07   73.0831  153.183  115.656
2020-01-08   74.2575  155.656  116.623
...              ...      ...      ...
2023-03-08  152.8700  253.700  128.050
2023-03-09  150.5900  252.320  126.160
2023-03-10  148.5000  248.590  125.450
2023-03-13  150.4700  253.920  125.580
2023-03-14  152.5900  260.790  124.650

[805 rows x 3 columns]

In [59]:
portfolios = [.45,.35,.20]

In [60]:
np.sum(portfolios)

1.0

In [62]:
data/data.iloc[0]*portfolios*1000

Symbols           AAPL        MSFT         IBM
2020-01-02  450.000000  350.000000  200.000000
2020-01-03  445.639573  345.702702  198.396162
2020-01-06  449.164374  346.592649  198.027759
2020-01-07  447.072861  343.387048  198.176833
2020-01-08  454.257044  348.930719  199.833790
...                ...         ...         ...
2023-03-08  935.155027  568.713853  219.413982
2023-03-09  921.207532  565.620337  216.175463
2023-03-10  908.422329  557.258875  214.958876
2023-03-13  920.473454  569.207022  215.181631
2023-03-14  933.442176  584.607354  213.588074

[805 rows x 3 columns]

In [65]:
weight = np.random.random(4)
weight /= weight.sum()
weight

array([0.29471351, 0.34967772, 0.31135371, 0.04425506])

In [66]:
weight.sum()

1.0